---
title: "TOPA blog"
output: html_document
date: "2025-10-13"
---


```{r libraries}

library(tidyverse)
library(readr)
library(readxl)
library(dplyr)
library(janitor)
library(stringr)
library(purrr)
library(here)
library(sjlabelled)
library(rstatix)
library(haven)
library(lubridate)
# install.packages("mapview")
library(mapview)
library(ggplot2)
# install.packages("remotes")
library(remotes)

# remotes::install_github("UrbanInstitute/urbnthemes")
library(urbnthemes)
set_urbn_defaults(style = "print")


```



```{r read in data files}

# Read in SAS dataset

rent_data = read_sas("//sas1/dcdata/Libraries/DHCD/Data/parcels_rent_control.sas7bdat") 


```


## Descriptives of 2-4 unit properties



```{r Descriptives}

### Creating variables for analysis ### 

rent_data = rent_data  %>% 
  # Removing English basement types
  filter(Sfh_extra_unit !=1) %>%
  # Binary 2-4 unit variable
  mutate(two_four_unit_flag = case_when(
    units_full %in% c(2,3,4) ~ "yes", 
    T ~ "no"
  ), 
  # categorical unit variable
  unit_count_cat = 
    case_when(
    units_full == 1 ~ "single-family", 
    units_full %in% c(2,3,4) ~ "2 to 4 units", 
    units_full >= 5 ~ "5 or more units",
    T ~ NA_character_
  ), 
# Corporate / non corporate owner binary  
owner_bin = case_when(Ownercat %in% c("020", "030", "040", "045", "050", "060", "090", "100") ~ "Non-corporate owner", 
T ~ "Corporate owner"),
# Using names for ownercat
Ownercat = case_when(
   Ownercat == "020" ~ "Multifamily owner-occupied" , 
    Ownercat ==	"030"	~ "Other individuals"	,
 	  Ownercat ==	 "040" ~ "DC government",
 	   Ownercat ==	"045"~ "DC Housing Authority",
  	  Ownercat =="050"~	"US government" ,
 	  Ownercat ==	 "060" ~"Foreign governments",
 		  Ownercat == "070"~ "Quasi-public entities",
 	  Ownercat == "080" ~	"Community development corporations/organizations",
    Ownercat ==		"090"~"Private universities, colleges, schools" ,
 	 	  Ownercat ==	"100"~ "Churches, synagogues, religious",
 	  Ownercat ==	"111" ~"Nontaxable corporations, partnerships, associations"	, 
 		  Ownercat == "115"~ "Taxable corporations, partnerships, associations",
 		   Ownercat == "120"~ "Government-Sponsored Enterprise",
 		   Ownercat == "130" ~ "Banks, Lending, Mortgage and Servicing Companies" 
  ))

## Create dataset for 2-4 unit properties

two_four_unit_data = rent_data %>% filter(units_full %in% c(2,3,4))


## How much of DC’s rental housing is in 2-4 unit buildings?

  # Of all rental properties
  rent_data %>% 
    group_by(two_four_unit_flag) %>%
    summarize(number_properties = n())%>%
    ungroup()%>%
    summarize(
      two_four_unit_flag = two_four_unit_flag, 
      number_properties = number_properties,
      percent = round(number_properties/sum(number_properties) * 100, digits = 2))


 ## Taking out single family and missing unit counts (used these in blog)

  # Number of properties by property type
  rent_data %>% 
    group_by(unit_count_cat) %>%
    filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
    summarize(number_properties = n())%>%
    ungroup()%>%
    summarize(
      unit_count_cat = unit_count_cat, 
      number_properties = number_properties,
      percent = round(number_properties/sum(number_properties) * 100, digits = 2))

  # Number of units by property type
  rent_data %>% 
    group_by(unit_count_cat) %>%
    filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
    summarize(number_units = sum(units_full))%>%
    ungroup()%>%
    summarize(
      unit_count_cat = unit_count_cat, 
      number_units = number_units,
      percent = round(number_units/sum(number_units) * 100, digits = 2))

### Where are these (2-4 unit) properties located? ###

# By Wards
rent_data %>% 
  filter(two_four_unit_flag == "yes") %>%
  group_by(Ward2022) %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    Ward2022 = Ward2022, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# Share of properties within wards

rent_data %>%
  filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
  group_by(two_four_unit_flag, Ward2022) %>%
  summarize(number_properties = n())%>%
  group_by(Ward2022)%>%
  summarize(
    Ward2022 = Ward2022, 
    two_four_unit_flag = two_four_unit_flag, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# By Neighborhood clusters
rent_data %>% 
  filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
  group_by(cluster2017) %>%
  filter(two_four_unit_flag == "yes") %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    cluster2017 = cluster2017, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# Share of properties within neighborhood clusters
rent_data %>%
  filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
 group_by(two_four_unit_flag, cluster2017) %>%
  summarize(number_properties = n())%>%
  group_by(cluster2017)%>%
  summarize(
    cluster2017 = cluster2017,
    two_four_unit_flag = two_four_unit_flag, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))


# Descending order - share of properties within neighborhood clusters that are 2-4 units
  rent_data %>%
    filter(unit_count_cat != "single-family" & !is.na(unit_count_cat)) %>%
  group_by(two_four_unit_flag, cluster2017) %>%
  summarize(number_properties = n())%>%
  group_by(cluster2017)%>%
  summarize(
    cluster2017 = cluster2017,
    two_four_unit_flag = two_four_unit_flag, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))%>%
  filter(two_four_unit_flag == "yes") %>%
  arrange(desc(percent))

  
### Who owns 2-4 unit buildings? ###

# Overall cut
rent_data %>% 
  filter(two_four_unit_flag == "yes" & !is.na(Ownercat)) %>%
  group_by(Ownercat) %>%
  summarize(number_properties = n())%>%
  summarize(
    Ownercat = Ownercat, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# Searching for "trust"
rent_data %>%
  mutate(trust_in_owner_name = case_when(
    str_detect(Ownername_full, "trust|Trust") ~ "yes", 
    is.na(Ownername_full) ~ NA_character_, 
    T ~ "no"
  )) %>%
  filter(two_four_unit_flag == "yes") %>%
  group_by(Ownercat, trust_in_owner_name) %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    Ownercat = Ownercat, 
    trust_in_owner_name = trust_in_owner_name,
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# How many unique trust_in_owner_name
rent_data %>%
  mutate(trust_in_owner_name = case_when(
    str_detect(Ownername_full, "trust|Trust") ~ "yes", 
    is.na(Ownername_full) ~ NA_character_, 
    T ~ "no"
  )) %>%
  filter(two_four_unit_flag == "yes" & trust_in_owner_name == "yes") %>%
  distinct(Ownername_full, .keep_all = T)

# How many "other individuals" owners with trust in name
rent_data %>%
   filter(Ownercat == "Other individuals") %>% 
  mutate(trust_in_owner_name = case_when(
    str_detect(Ownername_full, "trust|Trust") ~ "yes", 
    is.na(Ownername_full) ~ NA_character_, 
    T ~ "no"
  )) %>%
  filter(two_four_unit_flag == "yes") %>%
  group_by(Ownercat, trust_in_owner_name) %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    Ownercat = Ownercat, 
    trust_in_owner_name = trust_in_owner_name,
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))




  # How many "other individual" owners with unique trust name
    rent_data %>%
      filter(Ownercat == "Other individuals") %>% 
    mutate(trust_in_owner_name = case_when(
      str_detect(Ownername_full, "trust|Trust") ~ "yes", 
      is.na(Ownername_full) ~ NA_character_, 
      T ~ "no"
    )) %>%
    filter(two_four_unit_flag == "yes" & trust_in_owner_name == "yes") %>%
    distinct(Ownername_full, .keep_all = T)                                

### Are these properties subsidized? ###

rent_data %>% 
  filter(two_four_unit_flag == "yes") %>%
  group_by(Exempt_assisted) %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    Exempt_assisted = Exempt_assisted, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

  # Who owns the subsdized housing? 
  rent_data %>% 
    filter(two_four_unit_flag == "yes") %>%
    filter(Exempt_assisted == 1) %>%
    group_by(Ownercat) %>%
    summarize(number_properties = n())%>%
    ungroup()%>%
    summarize(
      Ownercat = Ownercat, 
      number_properties = number_properties,
      percent = round(number_properties/sum(number_properties) * 100, digits = 2))


## Age of buildings
rent_data %>%
  group_by(AYB_Min) %>%
  summarize(number_properties = n()) %>%
  ungroup()%>%
  summarize(
    AYB_Min = AYB_Min, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# 1980 cutoff 
rent_data %>%
  mutate(year_bin_1980 = case_when(
    AYB_Min < 1980 ~ 1, 
    is.na(AYB_Min) ~ NA_real_, 
    T ~ 0
  ))%>%
  group_by(year_bin_1980) %>%
  filter(!is.na(year_bin_1980)) %>%
   summarize(number_properties = n()) %>%
  ungroup()%>%
  summarize(
    year_bin_1980 = year_bin_1980, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))

# 1950 cutoff
rent_data %>%
  mutate(year_bin_1950 = case_when(
    AYB_Min < 1950 ~ 1, 
    is.na(AYB_Min) ~ NA_real_, 
    T ~ 0
  ))%>%
  group_by(year_bin_1950) %>%
  filter(!is.na(year_bin_1950)) %>%
   summarize(number_properties = n()) %>%
  ungroup()%>%
  summarize(
    year_bin_1950 = year_bin_1950, 
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))


### Searching for "LLC" ###
 rent_data %>%
  mutate(llc_in_owner_name = case_when(
    str_detect(Ownername_full, regex(" LLC", ignore_case = TRUE)) ~ "yes",
    str_detect(Ownername_full, regex("\\.LLC", ignore_case = TRUE)) ~ "yes", 
    str_detect(Ownername_full, regex("\\,LLC", ignore_case = TRUE)) ~ "yes", 
    is.na(Ownername_full) ~ NA_character_, 
    T ~ "no"
  )) %>%
  filter(two_four_unit_flag == "yes") %>%
  group_by(Ownercat, llc_in_owner_name) %>%
  summarize(number_properties = n())%>%
  ungroup()%>%
  summarize(
    Ownercat = Ownercat, 
    llc_in_owner_name = llc_in_owner_name,
    number_properties = number_properties,
    percent = round(number_properties/sum(number_properties) * 100, digits = 2))
 
 
```

## PLOTS

```{r graphics}

## 1) bar chart comparing 2-4 units and 5+ units number of properties

rent_data %>%
  filter(unit_count_cat %in% c("2 to 4 units", "5 or more units")) %>%
  count(unit_count_cat) %>%
  ggplot(aes(x = unit_count_cat, y = n)) + 
    geom_col() +
    labs(x = "Property type",
       y = "Total number of properties") +
  
  geom_text(mapping = aes(label = n), vjust = -1)  


## 2 ) bar chart comparing 2-4 units and 5+ units chart number of units.

rent_data %>%
  filter(unit_count_cat %in% c("2 to 4 units", "5 or more units")) %>%
  group_by(unit_count_cat) %>%
  summarize(units_count = sum(units_full))%>%
  ggplot(aes(x = unit_count_cat, y = units_count)) + 
    geom_col() +
    labs(x = "Property type",
       y = "Total number of units") +
  geom_text(aes(label = units_count), position = position_dodge(width = 0.7), vjust = -1.15) 


# Corporate and non-corporate with fill by ownercat - TOO MANY categories 
rent_data %>%
  filter(two_four_unit_flag == "yes") %>%
 group_by(owner_bin, Ownercat) %>%
 summarize(units_count = sum(units_full))%>%
  ggplot() +
  geom_bar(mapping = aes(x = owner_bin, fill = Ownercat), position = "fill") +
  # ggplot(aes(x = owner_bin, y = units_full, fill = Ownercat)) + 
  #  geom_col() +
    labs(x = "Ownership",
       y = "Percent of units") +
  ggplot2::scale_fill_discrete()
 # geom_text(aes(label = units_full), position = position_dodge(width = 0.7), vjust = -1.15) 

# Corporate and non-corporate with fill by ownercat (limited categories)
rent_data %>%
  filter(two_four_unit_flag == "yes") %>%
  mutate(owner_three_cat = case_when(
    str_detect(Ownercat, "occupied") ~"Multifamily owner-occupied", 
    str_detect(Ownercat, "individuals") ~ "Other individuals", 
    str_detect(Ownercat, "Taxable") ~ "Taxable corporations, partnerships, associations", 
    T ~ "All other owner types"
  )) %>%
  group_by(owner_three_cat)%>%
  count(owner_bin) %>%
  arrange(desc(owner_three_cat)) %>%
  
  mutate(label_height = cumsum(n)) %>%
  ggplot() +
  geom_col(mapping = aes(owner_bin, y=n, fill=owner_three_cat)) +
  


```


##  Case 1

```{r Case 1}

## Case 1: Nadeau
  ## Exemptions would extend to property owners of 2-4 unit buildings who kept these buildings in their own name, or in a living trust, and own no more than two rental properties in the District


## Look at owner type by category

two_four_unit_data %>% tabyl(Ownercat)
two_four_unit_data %>% tabyl(owneraddress)
two_four_unit_data %>% tabyl(Ownercat)


## Create flag for same owner 
  ## If name is the same OR address is the same

two_four_unit_data = two_four_unit_data %>% 
   left_join(
  two_four_unit_data %>% 
  group_by(Ownername_full) %>%
  summarize(owner_name_number = n()), 
  by = "Ownername_full") %>%
  mutate(
    owner_name_match = case_when(
      owner_name_number > 1 ~ "yes",
      owner_name_number <= 1 ~ "no", 
      T ~ NA_character_
    )
  ) %>%
  left_join(
    two_four_unit_data %>% 
  group_by(owneraddress) %>%
  summarize(owner_address_number = n()), 
  by = "owneraddress") %>%
    mutate(
    owner_address_match = case_when(
      owner_address_number > 1 ~ "yes",
      owner_address_number <= 1 ~ "no", 
      T ~ NA_character_
    ), 
    # Combined address or name match
    owner_name_or_address_match = case_when(
      owner_address_match == "yes" | owner_name_match == "yes" ~ "yes",
      is.na(owner_address_match) | is.na(owner_name_match) ~ NA_character_,
      T ~ "no"
    )
  ) 
   # Check - looks good
   # %>% tabyl(owner_address_match, owner_name_match, owner_name_or_address_match)


## Check this flag against pre-existing ownername_count in the original file 

 rent_data %>%
   left_join(
  rent_data %>% 
  group_by(Ownername_full) %>%
  summarize(owner_name_number = n()), 
  by = "Ownername_full") %>%
  mutate(
    owner_name_match = case_when(
      owner_name_number > 1 ~ "yes",
      owner_name_number <= 1 ~ "no", 
      T ~ NA_character_
    )
  ) %>%
  left_join(
    rent_data %>% 
  group_by(owneraddress) %>%
  summarize(owner_address_number = n()), 
  by = "owneraddress") %>%
    mutate(
    owner_address_match = case_when(
      owner_address_number > 1 ~ "yes",
      owner_address_number <= 1 ~ "no", 
      T ~ NA_character_
    ), 
    # Combined address or name match
    owner_name_or_address_match = case_when(
      owner_address_match == "yes" | owner_name_match == "yes" ~ "yes",
      is.na(owner_address_match) | is.na(owner_name_match) ~ NA_character_,
      T ~ "no"
    )
  ) %>%
    select(Ownername_count, owner_name_number, owner_address_number, owner_name_match, owner_name_or_address_match)


  two_four_unit_data %>% 
    tabyl(Ownername_count, owner_name_number)
  
  test = two_four_unit_data %>%
    filter(Ownername_count > 1) %>%
    select(Ownername_count, owner_name_match, owner_name_number, Ownername_full, OWNERNAME)


## Create flag for properties where same owner (based on name or address) owns two or fewer properties

two_four_unit_data = two_four_unit_data %>%
 
  mutate(owner_prop_number = case_when(
    owner_name_or_address_match == "no" ~ 1,
    owner_name_number == owner_address_number ~ owner_name_number,
    owner_name_number > owner_address_number ~ owner_name_number, 
    owner_address_number > owner_name_number ~ owner_address_number, 
    T ~ NA_real_
  )) %>%

  # Check - looks good
  # %>%
 # tabyl(owner_name_number, owner_address_number, owner_prop_number)

# Create binary flag for 2 or fewer properties
  mutate(owner_prop_number_2_less = case_when(
    owner_prop_number <= 2 ~ "yes", 
    owner_prop_number >2 ~ "no", 
    T ~ NA_character_
  ))
  # Check : two_four_unit_data %>% tabyl(owner_prop_number_2_less)
 

 ### Table 
  two_four_unit_data %>% tabyl(owner_prop_number_2_less)



### Create flag for meeting all of the Nadeau conditions

two_four_unit_data %>%
  mutate(nadeau_flag = case_when(
    owner_prop_number_2_less == "yes" & Ownercat %in% c("Multifamily owner-occupied", "Other individuals") ~ "yes", 
    is.na(owner_prop_number_2_less) & Ownercat %in% c("Multifamily owner-occupied", "Other individuals") ~ "maybe",
    T ~ "no"
  )) %>%
  tabyl(nadeau_flag)
  
  
  ## Just "other individuals" - not used. 
  two_four_unit_data %>%
  mutate(nadeau_flag = case_when(
    owner_prop_number_2_less == "yes" & Ownercat == "Other individuals" ~ "yes", 
    is.na(owner_prop_number_2_less) & Ownercat == "Other individuals" ~ "maybe",
    T ~ "no"
  )) %>%
  tabyl(nadeau_flag)

```

##  Case 2

```{r Case 2}

## Case 2: Bonds
  ## Exemption for any buildings with four or fewer units that do not have corporate ownership (majority ownership by business corporation)

# Summarize counts / pcts of corporate owned

two_four_unit_data %>%
  group_by(owner_bin)%>%
  summarize(number_properties = n())%>%
  summarize(owner_bin = owner_bin, 
            number_properties = number_properties, 
            percent_units = round(number_properties/sum(number_properties) * 100, digits = 2))

```

